In [ ]:
import math

print(math.pi)
print(math.sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import pi, sqrt

print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import *

print(pi)

3.141592653589793


In [1]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
import numpy.random

print(numpy.random.randn(3,3))

[[-0.51330237  0.6480529  -0.9021755 ]
 [ 1.58765544  0.30775825 -0.51621139]
 [ 0.85944925 -0.40050518  2.51767451]]


In [5]:
import numpy.random as nr

print(nr.randn(2,2))

[[-2.02707845 -0.37589201]
 [-0.51658626 -1.63589231]]


In [6]:
from numpy.random import *

print(rand(3,3))

[[0.18988681 0.49921245 0.73774949]
 [0.8230972  0.39921939 0.16850355]
 [0.99309265 0.31047928 0.94117273]]


In [15]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
print(a[0])
b = np.array([1,2,3.1,4])
print(b.dtype)
print(b[0])

[1 2 3 4]
<class 'numpy.ndarray'>
int32
(4,)
1
float64
1.0


In [16]:
a = np.array(2**64 -1)
print(a)
print(a.dtype)

18446744073709551615
uint64


In [20]:
a = np.array([[1,2], [3,4]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[1 2]
 [3 4]]
(2, 2)
2
4


In [28]:
print(np.zeros(5))
print(np.zeros_like(a))
print(np.ones(5))
print(np.zeros([3,3]))
print(np.arange(3,10,2))
print(np.arange(0,1,0.1))
print(np.linspace(0,1,10, endpoint=False))


[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
