In [ ]:
import math

print(math.pi)
print(math.sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import pi, sqrt

print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import *

print(pi)

3.141592653589793


In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
import numpy.random

print(numpy.random.randn(3,3))

[[-0.51330237  0.6480529  -0.9021755 ]
 [ 1.58765544  0.30775825 -0.51621139]
 [ 0.85944925 -0.40050518  2.51767451]]


In [5]:
import numpy.random as nr

print(nr.randn(2,2))

[[-2.02707845 -0.37589201]
 [-0.51658626 -1.63589231]]


In [6]:
from numpy.random import *

print(rand(3,3))

[[0.18988681 0.49921245 0.73774949]
 [0.8230972  0.39921939 0.16850355]
 [0.99309265 0.31047928 0.94117273]]


In [15]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
print(a[0])
b = np.array([1,2,3.1,4])
print(b.dtype)
print(b[0])

[1 2 3 4]
<class 'numpy.ndarray'>
int32
(4,)
1
float64
1.0


In [16]:
a = np.array(2**64 -1)
print(a)
print(a.dtype)

18446744073709551615
uint64


In [20]:
a = np.array([[1,2], [3,4]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[1 2]
 [3 4]]
(2, 2)
2
4


In [28]:
print(np.zeros(5))
print(np.zeros_like(a))
print(np.ones(5))
print(np.zeros([3,3]))
print(np.arange(3,10,2))
print(np.arange(0,1,0.1))
print(np.linspace(0,1,10, endpoint=False))


[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
print(c)

[5 7 9]


In [8]:
a = np.array([[1,2,3],[1,2,3]])
b = np.array([[4,5,6],[1,2,2]])
c = a + b
d = a - b
print(c)
print(d)
print()
print(a*b)
print(a/b)
print(a**b)

[[5 7 9]
 [2 4 5]]
[[-3 -3 -3]
 [ 0  0  1]]

[[ 4 10 18]
 [ 1  4  6]]
[[0.25 0.4  0.5 ]
 [1.   1.   1.5 ]]
[[  1  32 729]
 [  1   4   9]]


In [10]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print(a*b)
print(a@b)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


인덱싱 슬라이싱

In [16]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7 8 9]


In [27]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0])
print(a[-1])
print(a[1:])
print(a[:])
print(a[0][2])
print(a[0,2])
print(a[1,:])
print(a[1,0:3:2])
print(a[:,2])
b = [[1,2,3],[4,5,6],[7,8,9]]
print(b)
print(b[0][2])

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[4 5 6]
[4 6]
[3 6 9]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
3


In [36]:
# boolean indexing
a = [1,2,3,4,5,6,7]
print(a == 3)
b = np.array([[1,2,3,4],[5,3,7,3]])
print(b == 3)
print(b[b == 3])

b[b == 3] = 100 # 3 -->100 
print(b)

c = np.array([[1,2],[3,4],[5,6],[7,8]])
e = np.array([True, False, False, True])
c[e,:]

f = np.array([1,2,3,4])
print(f)
print(f[[True,True,False,False]])

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2 100   4]
 [  5 100   7 100]]
[1 2 3 4]
[1 2]


3차원 행렬의 인덱싱

In [37]:
a = np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],
                [[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
print(a)
print(a.shape)
print(a[0,1,2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6


In [42]:
a = np.random.randn(3,3)
b = np.random.rand(3,3)
print(a)
print(b)
print(a[a[:,0]<0,:])

[[ 0.94840484  0.38719732 -0.59010954]
 [-0.60534925  1.04449576  0.49256343]
 [ 0.46334254  0.68734056  0.19838177]]
[[0.2604406  0.85415601 0.55019863]
 [0.15132936 0.42262867 0.03500734]
 [0.60941977 0.1919445  0.34876687]]
[[-0.60534925  1.04449576  0.49256343]]


In [51]:
a = np.random.randn(3,3)
print(a)
print(np.abs(a))
print(np.sqrt(np.abs(a)))
print(np.exp(a))
print(np.log(np.abs(a)))
print(np.log(np.exp(1)))
print(np.log10(10))
print(np.log2(2))
print(np.round(a))
print(np.round(a,2))
print(np.floor(a))
print(np.ceil(a))

[[ 0.78801718  0.09274888 -0.27864371]
 [ 0.39118014  0.17711228  0.43003054]
 [-1.30645262 -0.84186887  0.5755265 ]]
[[0.78801718 0.09274888 0.27864371]
 [0.39118014 0.17711228 0.43003054]
 [1.30645262 0.84186887 0.5755265 ]]
[[0.88770332 0.304547   0.52786713]
 [0.62544395 0.4208471  0.65576714]
 [1.14300158 0.91753413 0.75863463]]
[[2.19903182 1.09718617 0.7568095 ]
 [1.47872486 1.19376513 1.53730448]
 [0.27077891 0.43090446 1.77806644]]
[[-0.23823539 -2.37785968 -1.27782135]
 [-0.93858712 -1.73097138 -0.84389904]
 [ 0.26731554 -0.17213101 -0.55247   ]]
1.0
1.0
1.0
[[ 1.  0. -0.]
 [ 0.  0.  0.]
 [-1. -1.  1.]]
[[ 0.79  0.09 -0.28]
 [ 0.39  0.18  0.43]
 [-1.31 -0.84  0.58]]
[[ 0.  0. -1.]
 [ 0.  0.  0.]
 [-2. -1.  0.]]
[[ 1.  1. -0.]
 [ 1.  1.  1.]
 [-1. -0.  1.]]


In [55]:
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
print(np.tan(np.pi/4))
print(np.tanh(10))

0.49999999999999994
0.5000000000000001
0.9999999999999999
0.9999999958776927


In [62]:
np.nan
print(np.isnan([1,2,np.nan,3,4]))
print(np.isinf([1,2,np.inf,3,4]))

[False False  True False False]
[False False  True False False]


In [72]:
a = np.random.randn(3,4)
print(a)
print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))
print(np.max(a,axis=0, keepdims=True))
print(np.max(a,axis=1, keepdims=True))
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))
print(np.min(a,axis=0, keepdims=True))
print(np.min(a,axis=1, keepdims=True))
print(np.argmax(a))
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

[[ 0.24325174 -0.45724653  1.65405927  0.1920749 ]
 [-1.20203543 -2.36262261 -0.71989468 -0.27205332]
 [-0.33246388 -1.10635206  0.7391323  -0.70887592]]
1.6540592749575
[ 0.24325174 -0.45724653  1.65405927  0.1920749 ]
[ 1.65405927 -0.27205332  0.7391323 ]
[[ 0.24325174 -0.45724653  1.65405927  0.1920749 ]]
[[ 1.65405927]
 [-0.27205332]
 [ 0.7391323 ]]
-2.3626226106480117
[-1.20203543 -2.36262261 -0.71989468 -0.70887592]
[-0.45724653 -2.36262261 -1.10635206]
[[-1.20203543 -2.36262261 -0.71989468 -0.70887592]]
[[-0.45724653]
 [-2.36262261]
 [-1.10635206]]
2
[0 0 0 0]
[2 3 2]


In [75]:
a = np.random.randn(6,1)
print(a)
a_sorted = np.sort(a,axis=0)
print(a_sorted)
print(np.flipud(a_sorted))

[[ 0.23580371]
 [ 0.20766907]
 [-0.55156395]
 [-0.87400247]
 [ 0.58350331]
 [-1.03962155]]
[[-1.03962155]
 [-0.87400247]
 [-0.55156395]
 [ 0.20766907]
 [ 0.23580371]
 [ 0.58350331]]
[[ 0.58350331]
 [ 0.23580371]
 [ 0.20766907]
 [-0.55156395]
 [-0.87400247]
 [-1.03962155]]


In [77]:
a = np.random.randn(3,4)
print(a)
print(np.sum(a))
print(np.sum(a,axis=1))
print(np.sum(a,axis=1, keepdims=True))
print(np.mean(a))
print(np.mean(a,axis=1))
print(np.mean(a,axis=1, keepdims=True))
print(np.std(a)) # 표준편차

[[-0.01287089 -0.62543933 -0.45127174  1.21345826]
 [ 1.1817651   1.05309949 -1.05346268  0.63850141]
 [ 0.36951283 -0.14685502 -1.38154077 -1.32252335]]
-0.5376267050516097
[ 0.12387629  1.81990332 -2.48140631]
[[ 0.12387629]
 [ 1.81990332]
 [-2.48140631]]
-0.04480222542096748
[ 0.03096907  0.45497583 -0.62035158]
[[ 0.03096907]
 [ 0.45497583]
 [-0.62035158]]
0.9074811420258089


In [81]:
a = np.random.randint(1,5,size=(12,))
print(a)
print(a.shape)
b = a.reshape(2,2,3)
print(b)
print(b.ndim)

[1 1 3 3 3 3 3 3 1 4 2 3]
(12,)
[[[1 1 3]
  [3 3 3]]

 [[3 3 1]
  [4 2 3]]]
3


In [87]:
a = np.array([1,2,3])
b = np.array([2,2,1])
print(np.sum(a*b))

a = a.reshape(3,1)
b = b.reshape(3,1)
print(a.transpose()@b)
print(a.T@b)

a = np.random.randn(4,3,2)
print(a.transpose(0,1,2).shape)

9
[[9]]
[[9]]
(4, 3, 2)


In [95]:
a = np.arange(20)
print(a)
print(a.reshape(4,5))
print(a.reshape(4,-1).shape)
print(a.reshape(2,5,-1))
print(a.reshape(2,5,-1).shape)
print(a.reshape(1,-1))
print(a.reshape(-1,1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [104]:
a = np.random.randn(2,3,4,5,6)
print(a[1,2,:,:,:])
print(a[1,2,:,:,:].shape)
print(a[1,2,...].shape)
print(a[:,:,:,:,3].shape)
print(a[...,3].shape)
print(a[1,...,3,:].shape)

[[[-0.37461377 -0.57268998  0.57760971 -0.78894102  0.700795
   -1.77842892]
  [-1.14509401 -0.44694476  0.07752718  0.42538582 -1.4265575
   -1.49027117]
  [ 0.85300797  0.57265139 -1.45493159 -0.01255565 -1.68047159
    0.21984906]
  [-2.51797105  0.36786616 -0.16577148 -0.14841591 -0.23312401
   -0.68865842]
  [ 0.51142385 -0.6010772   0.56900877  0.22386975 -1.99461301
    0.97123603]]

 [[ 1.09130296 -0.65114437  1.01183131  1.18298331  0.2359778
    1.67150776]
  [-1.13493663  0.47369945  1.68808516  0.04213243 -1.69756075
   -0.10905687]
  [-0.31264468 -3.00796768  1.29419772  1.66527383  1.31160266
    0.52665095]
  [-0.65911728 -0.39958625 -0.35147259  0.28285277  1.26349355
    0.66336948]
  [ 0.64892403  0.56275781  0.218793   -0.37562301  1.26307023
   -2.07794153]]

 [[-0.26103102 -2.22155958 -0.10142862 -0.78744635 -0.27347516
   -0.1064776 ]
  [ 0.54645333 -1.17824109 -0.618926    0.57451744 -0.74449148
   -0.65504312]
  [ 0.47872048  1.55301719 -0.29093762  0.55818083 -

In [109]:
a = np.ones((2,2))
b = np.zeros((2,2))
c = np.hstack([a,b])
d = np.vstack([a,b])
e = np.block([a,b])
f = np.block([[a],[b]])
g = np.block([[[a]],[[b]]])
print(c)
print(d)
print(e)
print(f)
print(g)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]


In [114]:
a = np.random.randn(1,1,1,3,1,1,4,1)
print(a.shape)
print(a.squeeze().shape)
print(a.squeeze(axis=(0,2,4,5)).shape)



(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [126]:
a = np.random.randn(3,4)
a1 = a[np.newaxis,...]

print(a1)
print(a1.shape)

a1 = a[None,...]
print(a1)
print(a1.shape)

a2 = a[...,np.newaxis]
print(a2)
print(a2.shape)

a3 = np.expand_dims(a,axis=0)
print(a3.shape)
a4 = np.expand_dims(a,axis=2)
print(a4.shape)
a5 = np.expand_dims(a,axis=1)
print(a5.shape)

a6 = a.reshape(1,3,4)
print(a6)
print(a6.shape)
a7 = a.reshape(3,4,1)
print(a7)
print(a7.shape)
a8 = a.reshape(3,1,4)
print(a8)
print(a8.shape)

[[[ 2.85553624  0.00881952 -1.30054022  1.07823281]
  [ 0.81592378  1.55239357 -1.80692622 -0.60022185]
  [ 0.21024676  1.24613724  0.67299956 -0.56780276]]]
(1, 3, 4)
[[[ 2.85553624  0.00881952 -1.30054022  1.07823281]
  [ 0.81592378  1.55239357 -1.80692622 -0.60022185]
  [ 0.21024676  1.24613724  0.67299956 -0.56780276]]]
(1, 3, 4)
[[[ 2.85553624]
  [ 0.00881952]
  [-1.30054022]
  [ 1.07823281]]

 [[ 0.81592378]
  [ 1.55239357]
  [-1.80692622]
  [-0.60022185]]

 [[ 0.21024676]
  [ 1.24613724]
  [ 0.67299956]
  [-0.56780276]]]
(3, 4, 1)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
[[[ 2.85553624  0.00881952 -1.30054022  1.07823281]
  [ 0.81592378  1.55239357 -1.80692622 -0.60022185]
  [ 0.21024676  1.24613724  0.67299956 -0.56780276]]]
(1, 3, 4)
[[[ 2.85553624]
  [ 0.00881952]
  [-1.30054022]
  [ 1.07823281]]

 [[ 0.81592378]
  [ 1.55239357]
  [-1.80692622]
  [-0.60022185]]

 [[ 0.21024676]
  [ 1.24613724]
  [ 0.67299956]
  [-0.56780276]]]
(3, 4, 1)
[[[ 2.85553624  0.00881952 -1.30054022  1.07823281